### PR TITLE
buffer reads from sha3

### PR DESCRIPTION
**Pull request by josharian**
When added atop the sha3 alloc improvements in https://go.dev/cl/544817:

```
goos: darwin
goarch: arm64
pkg: filippo.io/mlkem768
            │   4b2bb98   │           e9cd519           │
            │   sec/op    │   sec/op     vs base        │
SampleNTT-8   1.994µ ± 0%   1.434µ ± 0%  -28.08% (n=50)
KeyGen-8      48.03µ ± 0%   41.96µ ± 1%  -12.63% (n=50)
Encaps-8      66.51µ ± 0%   59.98µ ± 0%   -9.81% (n=50)
Decaps-8      79.32µ ± 0%   72.91µ ± 0%   -8.08% (n=50)
RoundTrip-8   200.0µ ± 0%   187.1µ ± 0%   -6.43% (n=50)
geomean       39.89µ        34.55µ       -13.39%
```

### CODE REVIEW

**Comment by josharian** [comment]
Another thing you could patch atop this, if you want, that shaves another ~1.5% on arm64: https://github.com/josharian/mlkem768/commit/db20f6cdd01790542d4456124cf33bf351f3be4a

**Comment by FiloSottile** [comment]
Awesome! I had actually tried buffering and somehow I didn't manage to get an effect out of it (2e6a3dff2e6cd860e36a8b439c1765e14c5d3a0f). Thank you ✨ 

```
goos: linux
goarch: amd64
pkg: filippo.io/mlkem768
cpu: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
name         old time/op  new time/op  delta
SampleNTT-4  3.13µs ± 1%  2.22µs ± 0%  -29.03%  (p=0.000 n=10+9)
KeyGen-4     85.9µs ± 1%  73.9µs ± 1%  -13.95%  (p=0.000 n=10+10)
Encaps-4      123µs ± 1%   112µs ± 0%   -8.99%  (p=0.000 n=10+7)
Decaps-4      148µs ± 0%   136µs ± 1%   -7.90%  (p=0.000 n=9+10)
RoundTrip-4   360µs ± 0%   339µs ± 0%   -5.86%  (p=0.000 n=9+10)
```

**Comment by FiloSottile** [comment]
Huh, weird, I consistently get a strongly negative effect from https://github.com/josharian/mlkem768/commit/db20f6cdd01790542d4456124cf33bf351f3be4a and arm64 though.

```
name         old time/op  new time/op  delta
SampleNTT-8  2.57µs ± 0%  2.81µs ± 0%  +9.40%  (p=0.000 n=10+10)
KeyGen-8     71.3µs ± 2%  74.6µs ± 4%  +4.50%  (p=0.000 n=10+10)
Encaps-8      101µs ± 1%   104µs ± 1%  +3.26%  (p=0.000 n=9+8)
Decaps-8      121µs ± 1%   124µs ± 1%  +2.76%  (p=0.000 n=10+10)
RoundTrip-8   313µs ± 0%   319µs ± 0%  +1.74%  (p=0.000 n=10+10)
```

While on amd64 the effect is positive.

```
name         old time/op  new time/op  delta
SampleNTT-4  2.31µs ± 1%  2.16µs ± 1%  -6.53%  (p=0.000 n=10+10)
KeyGen-4     76.9µs ± 2%  73.8µs ± 1%  -4.12%  (p=0.000 n=10+10)
Encaps-4      113µs ± 1%   112µs ± 1%  -1.19%  (p=0.000 n=9+10)
Decaps-4      139µs ± 1%   136µs ± 1%  -2.07%  (p=0.000 n=10+10)
RoundTrip-4   342µs ± 0%   335µs ± 0%  -2.17%  (p=0.000 n=8+9)
```

I just patched the commit on top of this PR, on top of main, with a replace for https://go.dev/cl/544817.

**Comment by FiloSottile** [comment]
🤦 I had not committed the replace directive, so what I was comparing in https://github.com/FiloSottile/mlkem768/pull/1#issuecomment-1840547660 was fd793ab-without-CL544817 (in a clean worktree) vs fd793ab+db20f6c+CL544817.

That explains _some_ of the weirdness.

However, I guess the question now is why CL 544817 seems to have a negative effect on arm64.

**Comment by FiloSottile** [comment]
Indeed, CL 544817 (and the previous in the stack) have a negative performance effect on arm64, and a positive one on amd64, even after all these patches.

```
goos: darwin
goarch: arm64
pkg: filippo.io/mlkem768
name         old time/op  new time/op   delta
SampleNTT-8  2.51µs ± 0%   2.80µs ± 0%  +11.57%  (p=0.000 n=7+10)
KeyGen-8     69.3µs ± 1%   72.0µs ± 1%   +3.87%  (p=0.000 n=9+9)
Encaps-8     96.1µs ± 1%  100.2µs ± 1%   +4.25%  (p=0.000 n=9+10)
Decaps-8      116µs ± 1%    120µs ± 1%   +3.65%  (p=0.000 n=10+10)
RoundTrip-8   299µs ± 0%    310µs ± 0%   +3.97%  (p=0.000 n=10+9)
```

```
goos: linux
goarch: amd64
pkg: filippo.io/mlkem768
cpu: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
name         old time/op  new time/op  delta
SampleNTT-4  2.26µs ± 1%  2.15µs ± 0%  -4.62%  (p=0.000 n=9+8)
KeyGen-4     72.9µs ± 1%  70.8µs ± 1%  -2.90%  (p=0.000 n=9+9)
Encaps-4      109µs ± 1%   107µs ± 1%  -1.89%  (p=0.000 n=10+10)
Decaps-4      133µs ± 2%   131µs ± 1%  -2.00%  (p=0.000 n=10+10)
RoundTrip-4   328µs ± 1%   323µs ± 1%  -1.36%  (p=0.000 n=10+10)
```

Anyway. These patches have a positive impact regardless. Submitting them, thank you!

**Comment by josharian** [comment]
> I consistently get a strongly negative effect from https://github.com/josharian/mlkem768/commit/db20f6cdd01790542d4456124cf33bf351f3be4a and arm64 though.

Huh. Maybe your arm64 isn't happy with unaligned reads. Shrug. Computers are hard. :) Glad some of it was useful.

**Comment by FiloSottile** [comment]
> > I consistently get a strongly negative effect from [josharian@db20f6c](https://github.com/josharian/mlkem768/commit/db20f6cdd01790542d4456124cf33bf351f3be4a) and arm64 though.
> 
> Huh. Maybe your arm64 isn't happy with unaligned reads. 

Nono I think I was actually measuring the (still puzzling) negative effect of CL 544817 by mistake. https://github.com/FiloSottile/mlkem768/pull/1#issuecomment-1840642882

**Pull request closed without merging**
